-- Create working tournaments that users can join
INSERT INTO tournaments (
  id,
  name,
  tournament_type,
  description,
  status,
  game,
  prize_pool,
  entry_fee,
  start_date,
  end_date,
  max_participants,
  player_pool_settings,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Weekly Draft Championship',
  'draft',
  'Join our weekly draft tournament with snake draft format',
  'active',
  'zealot_hockey',
  500.00,
  25.00,
  NOW() + INTERVAL '2 hours',
  NOW() + INTERVAL '1 week',
  16,
  '{"draft_mode": "snake_draft", "teams_per_match": 2, "players_per_team": 4, "auto_start": true}',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Auction Draft Masters',
  'draft',
  'High stakes auction draft tournament for experienced players',
  'active',
  'zealot_hockey',
  1000.00,
  50.00,
  NOW() + INTERVAL '4 hours',
  NOW() + INTERVAL '1 week',
  12,
  '{"draft_mode": "auction_draft", "teams_per_match": 2, "players_per_team": 4, "auto_start": true}',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Beginner Linear Draft',
  'draft',
  'Perfect for new players - linear draft format with lower entry fee',
  'active',
  'zealot_hockey',
  200.00,
  10.00,
  NOW() + INTERVAL '6 hours',
  NOW() + INTERVAL '1 week',
  20,
  '{"draft_mode": "linear_draft", "teams_per_match": 2, "players_per_team": 4, "auto_start": true}',
  NOW(),
  NOW()
);
